HOMOPHONES = {
    'above': {'about', 'out of'},
    'ask': {'at', 'asking'},
    'atom': {'adam', 'at them'},
    'begin': {'began'},
    'below': {'the low', 'a low'},
    'bike': {'spike', 'pick', 'biker', 'bite', 'like', 'pike'},
    'bill': {'phil', 'build', 'built', 'will'},
    'block': {'blocks', 'walk', 'law'},
    'blue': {'blew'},
    'bookmarks': {'books', 'bookmark'},
    'boat': {'boats'},
    'bow': {'bo', 'bowel', 'both', 'bal'},
    'braces': {'places', 'place', 'brace', 'race', 'embrace'},
    'brain': {'rain'},
    'buffer': {'butter'},
    'cake': {'take', 'k', 'kick'},
    'call': {'called'},
    'camel': {'kimmel'},
    'capitalize': {},
    'carb': {'car', 'carbon', 'car of', 'card'},
    'cat': {"can't", 'to get', 'cans', 'cats', 'catch', 'kat'},
    'check': {'checks', 'checked'},
    'class': {'blast'},
    'climb': {'client', 'climbed', 'climate'},
    'comment': {'comments'},
    'copy': {'coffee', 'copies'},
    'create': {'creates'},
    'cut': {'collect'},
    'dam': {'band', 'damn', 'man', 'dan'},
    'dell': {"they'll", 'now', 'del'},
    'dir': {'dear', 'deer'},
    'disable': {'disabled'},
    'display': {'displayed', 'displays'},
    'django': {'jingle', 'jingo', 'jango', 'mango', 'gang of', 'tango',
               'jungle', 'can go', 'jangle', 'general', 'can go', 'jane',
               'j go', 'jago', 'genco', 'chang down', 'chang go'},
    'dock': {'doc', 'docs'},
    'drive': {'jive'},
    'drop': {'dropped', 'prop', 'draw'},
    'elephant': {'elephants'},
    'enter': {'and there'},
    'enumerate': {'enumerated', 'in numerate'},
    'eve': {'e', 'even', 'ethan', 'yves', 'eat', 'leave', 'steve', 'eve'},
    'flat': {'fat'},
    'first': {'1st'},
    'fish': {'dish', 'dished', 'pitch', 'finished', 'fiction', 'page', 'fishing', 'efficient', 'fisher', '-ish'},
    'flat': {'flats'},
    'foot': {'but'},
    'frog': {'fog', 'dog', 'for the', 'prague', 'log', 'fraud', 'broad', 'froggy'},
    'function': {'functions', 'functioning'},
    'fuzzy': {'by the', 'as he'},
    'git': {'get'},
    'grab': {'lab', 'crab', 'grad', 'grout', 'grabbed'},
    'green': {'clean', 'cream'},
    'grow': {'growth', 'grove', 'grows', 'of row', 'grow it'},
    'gun': {'done', 'gone', 'bun'},
    'halt': {'alt','fault', 'hold', 'holt', 'holds', 'faults', 'halts'},
    'ice': {'nice', 'i', 'price'},
    'if': {'f'},
    'job': {'jobs', 'chop'},
    'jump': {'jumps', 'jumped'},
    'kill': {'killed', 'kills', 'kilt', 'gil', 'pill', 'hill', 'kiln', 'killer', 'by', 'kilo'},
    'halt': {'hans', 'halts', 'taught', 'holt'},
    'high': {'hi', 'hide', 'hike', 'tied', 'height', 'i', 'hyde'},
    'lapse': {'laps', 'lapsed', 'lapsing', 'labs'},
    'leap': {'fleet'},
    'left': {'last'},
    'lend': {'land', 'lender', 'went', 'blend'},
    'line': {'wine', 'lawn', 'white', 'lines', 'loin', 'lying', 'blindly', 'one', 'lined'},
    'link': {'like', 'lake', 'wink', 'think'},
    'list': {'west', 'lest', 'w.'},
    'lit': {"let's", 'wet'},
    'live': {'life', 'lived', 'lives'},
    'low': {'love', 'o', 'oh', 'load', 'flow'},
    'macro': {'mac or', 'crow', 'mac rd.'},
    'map': {'matt'},
    'mark': {'arc'},
    'mint': {'meant', "didn't", 'mitt'},
    'mod': {'modest'},
    'music': {'using'},
    'need': {'knee', 'kneed', 'me', 'needed', 'snead'},
    'nerd': {'learned', 'third', 'noted'},
    'none': {'non-'},
    'num': {'numb', 'gnome'},
    'open': {'opened', 'opens', 'opening', 'over'},
    'out': {'outs'},
    'paint': {'pain', 'paints', 'painter'},
    'pair': {'parent', "parent's", 'parents', 'para', 'payer', 'paris', 'pear', 'there'},
    'paste': {'based', 'paced'},
    'path': {'pass', 'past'},
    'perl': {'pearl', 'rural', 'moral', 'all'},
    'plant': {'plants', 'plan to'},
    'play': {'played', 'plays', 'playing', 'plate'},
    'poke': {'hope', 'poked', 'polk', 'pope', 'focus'},
    'project': {'product'},
    'punch': {'punched', 'punches'},
    'quad': {'quart'},
    'queue': {'cue', 'q'},
    'queues': {'cues'},
    'recur': {'occur', 'weaker'},
    'record': {'recorder', 'recorded', 'records'},
    'relpath': {'rel path'},
    'rib': {'red', 'webb', 'ridden', 'rid', 'ribbon'},
    'right': {'rights', 'light', 'write', 'rate'},
    'ring': {'rang'},
    'risk': {'rest', 'rescue', 'brisk'},
    'root': {'roots', 'route', 'routes'},
    'rose': {'rows'},
    'sail': {'sale'},
    'save': {'safe', 'saves', 'saved'},
    'say': {'z'},
    'score': {'sore', 'escort', 'core', 'sort', 'sport', 'support', 'scoring'},
    'select': {'selected'},
    'shell': {'shall'},
    'short': {'should', 'shorts'},
    'single': {'angle', 'sing', 'singled', 'singles'},
    'slap': {'slot', '/', 'sap', 'flap', 'slump', 'slop', 'slapped'},
    'slip': {'slit', 'flip', 'slept'},
    'space': {'sais', 'spaced'},
    'spine': {'explain'},
    'straight': {'straights'},
    'start': {'skirt', 'starts', 'starting', 'started', 'serve'},
    'string': {'strings', 'strengths', 'strength', 'strain'},
    'strip': {'strap'},
    'stop': {'stopped', 'stops'},
    'surround': {'surrounded', 'surrounds'},
    'sys': {'cysts'},
    'title': {'titled', 'tidal'},
    'tab': {'have'},
    'tag': {'tab', 'tan'},
    'tail': {'tale', 'detail'},
    'tall': {'paul', 'tal'},
    'till': {'tilt'},
    'top': {'cop'},
    'touch': {'touched'},
    'trip': {'trap', 'chip'},
    'trunk': {'truck', 'drunk', 'took', 'chunk', 'strung'},
    'tuple': {'tubal'},
    'uniform': {'you want', 'cuneiform'},
    'until': {'on till'},
    'update': {'updates'},
    'variable': {'very important'},
    'vault': {'salt', 'vaults'},
    'viewport': {'viewports'},
    'vim': {'them'},
    'vote': {'votes', 'folk', 'folks', 'though'},
    'war': {'warp', 'warps', 'warped', 'wore', 'ward', 'award'},
    'wave': {'dave', 'ways', 'leave', 'will leave', 'wayne', 'waive'},
    'wig': {'weak', 'week'},
    'window': {'when the', 'when', 'in the'},
    'word': {'words'},
    'z': {'is owned', 'sewn'},
}

NUMBERS_MAP = {
    'zero': '0',
    'one': '1',
    'two': '2',
    'three': '3',
    'four': '4',
    'five': '5',
    'six': '6',
    'seven': '7',
    'eight': '8',
    'nine': '9',
    'won': '1',
    'to': '2',
    'too': '2',
    'do': '2',
    'free': '3',
    'for': '4',
    "i've": '5',
    'sets': '6',
    'sex': '6',
    'mine': '9',
}

GLOBAL_CONTEXTS = {
    'language': 'python'
}
